/**
 * 业务异常码 — 前后端共用，避免各写一套字符串。
 * 后续按 prds/05-api 扩展；此处仅基线 + 系统占位。
 */
export const BizCode = {
  COMMON_INVALID_REQUEST: 'COMMON.INVALID_REQUEST',
  COMMON_NOT_FOUND: 'COMMON.NOT_FOUND',
  AUTH_UNAUTHORIZED: 'AUTH.UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH.FORBIDDEN',
  AUTH_INVALID_CREDENTIALS: 'AUTH.INVALID_CREDENTIALS',
  BIZ_CONFLICT: 'BIZ.CONFLICT',
  BIZ_RULE_VIOLATION: 'BIZ.RULE_VIOLATION',
  SYSTEM_INTERNAL_ERROR: 'SYSTEM.INTERNAL_ERROR',
  SYSTEM_UPSTREAM_TIMEOUT: 'SYSTEM.UPSTREAM_TIMEOUT',
  SYSTEM_NOT_READY: 'SYSTEM.NOT_READY',
} as const;

export type BizCode = (typeof BizCode)[keyof typeof BizCode];
